---
- name: Run pre-test steps
  ansible.builtin.import_playbook: pre-test-steps.yml

- name: "Verify logging projects, endpoints, credentials, nodes, pods, services, manifests and subscriptions"
  hosts: controller
  gather_facts: no
  ignore_errors: true
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  vars_files:
    - vars/osp18_env.yml
  vars:
    common_subscription_test_id: ""
    common_subscription_nspace: openshift-operators-redhat
    common_subscription_list:
      - loki-operator

    common_endpoint_test_id: ""
    common_endpoint_list:
      - [cloudkitty,rating,public]
      - [cloudkitty,rating,internal]

    common_service_test_id: ""
    common_service_nspace: openstack
    common_service_list:
      - cloudkitty-lokistack-compactor-grpc
      - cloudkitty-lokistack-compactor-http
      - cloudkitty-lokistack-distributor-grpc
      - cloudkitty-lokistack-distributor-http
      - cloudkitty-lokistack-gateway-http
      - cloudkitty-lokistack-gossip-ring
      - cloudkitty-lokistack-index-gateway-grpc
      - cloudkitty-lokistack-index-gateway-http
      - cloudkitty-lokistack-ingester-grpc
      - cloudkitty-lokistack-ingester-http
      - cloudkitty-lokistack-querier-grpc
      - cloudkitty-lokistack-querier-http
      - cloudkitty-lokistack-query-frontend-grpc
      - cloudkitty-lokistack-query-frontend-http

  tasks:
    - name: "Verify logging infrastructure components"
      ansible.builtin.import_role:
        name: common


- name: "Verify logging pods are running in openstack"
  hosts: controller
  gather_facts: no
  ignore_errors: true
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  vars:
    common_pod_test_id: ""
    common_pod_status_str: "Running"
    common_pod_nspace: openstack
    common_pod_list:
      - openstackclient
  tasks:
    - name: "Verify Running Pods"
      ansible.builtin.import_role:
        name: common


- name: "Verify logging pods are running in openshift-operators-redhat"
  hosts: controller
  gather_facts: no
  ignore_errors: true
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  vars:
    common_pod_test_id: ""
    common_pod_status_str: "Running"
    common_pod_nspace: openshift-operators-redhat
    common_pod_list:
      - loki-operator-controller-manager
  tasks:
    - name: "Verify Pods running"
      ansible.builtin.import_role:
        name: common

- name: "Verify minio is runing in minio-dev"
  hosts: controller
  gather_facts: no
  ignore_errors: true
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  vars:
    common_pod_test_id: ""
    common_pod_status_str: "Running"
    common_pod_nspace: minio-dev
    common_pod_list:
      - minio
    common_crd_test_id: ""
    common_crd_list:
      - alertingrules.loki.grafana.com
      - lokistacks.loki.grafana.com
      - recordingrules.loki.grafana.com
      - rulerconfigs.loki.grafana.com
  tasks:
    - name: "Run Services and CRD tests"
      ansible.builtin.import_role:
        name: common
    - name: "Run the chargeback role"
      ansible.builtin.import_role:
        name: observe_chargeback

