---
- name: Run telemetry tests to verify metrics on osp18
  hosts:  "{{ cifmw_target_hook_host | default('localhost')  }}"
  gather_facts: true
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}:/var/lib/ansible/bin"
  vars_files:
    - vars/common.yml
    - vars/osp18_env.yml
  tasks:
    - name: Include vars from the extra_vars files
      when: cifmw_basedir is defined
      ansible.builtin.include_vars:
        dir: "{{ cifmw_basedir }}/artifacts/parameters"

    - name: Install oc
      ansible.builtin.include_role:
        name: cifmw.general.ci_setup
        tasks_from: packages
      vars:
        cifmw_ci_setup_packages: []

    - name: Log into openshift
      ansible.builtin.shell:
        cmd: |
          oc login -u {{ cifmw_openshift_user }} -p {{ cifmw_openshift_password }} --insecure-skip-tls-verify {{ cifmw_openshift_api }}
      register: cmd
      retries: 10
      delay: 10
      until: cmd.rc == 0

    - name: Patch observabilityclient into openstackclient
      ansible.builtin.shell:
        cmd: |
          oc exec openstackclient -- python3 -m ensurepip --upgrade
          oc exec openstackclient -- python3 -m pip install --upgrade aodhclient
          oc exec openstackclient -- python3 -m pip install --upgrade python-observabilityclient
      when: patch_observabilityclient | default(false) | bool
      tags:
        - setup

    - name: "Run Telemetry Verify Metrics tests"
      ansible.builtin.import_role:
        name: infrawatch.fvt.telemetry_verify_metrics
      ignore_errors: true
