---
- name: Run pre-test steps
  ansible.builtin.import_playbook: pre-test-steps.yml

- name: Run cloudkitty tests on osp18
  hosts:  "{{ cifmw_target_hook_host | default('localhost')  }}"
  gather_facts: true
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  vars_files:
    - vars/common.yml
    - vars/osp18_env.yml
  tasks:
    - block:
        # TODO: consider mounting these dirs into the pod
        #- name: Include vars from the extra_vars files
        #    ansible.builtin.include_vars:
        #      dir: "{{ cifmw_basedir }}/artifacts/parameters"

        - name: Patch cloudkittyclient into openstackclient
          ansible.builtin.shell:
            cmd: |
              oc exec -n openstack openstackclient -- python3 -m ensurepip --upgrade
              oc exec -n openstack openstackclient -- python3 -m pip install --upgrade git+https://github.com/openstack/python-cloudkittyclient@stable/2025.2

        # There should be a metric storage endpoint available
        # Lokistack should exist
        #
        - name: Set some vars
          ansible.builtin.set_fact:
            service_name: instance
            group_name: instance_uptime_flavor_id
            field_name: flavor_id
            #export FLAVOR_NAME=m1.micro
            flavor_name: "test_flavor"

        - name: Create the expected flavor
          ansible.builtin.shell:
            cmd: |
              {{ openstack_cmd }} flavor create --ram 128 --disk 20 --vcpus 1 {{ flavor_name }}

        - name: Check that the API is available
          ansible.builtin.shell:
            cmd: |
              # export SERVICE_NAME=instance
              # export GROUP_NAME=instance_uptime_flavor_id
              # export FIELD_NAME="flavor_id"

              {{ openstack_cmd }} rating module list
              {{ openstack_cmd }} rating hashmap group create {{ group_name }}
              #export GROUP_ID=$( {{ openstack_cmd }} rating group list -f value -c Name -c 'Group ID' | grep {{ group_name }} | awk '{ print $2}')
          ignore_errors: true

        - name: Get the group ID
          ansible.builtin.shell:
            cmd: |
              {{ openstack_cmd }} rating group list -f value -c Name -c 'Group ID' | grep {{ group_name }} | awk '{ print $2}'
          register: group_id

        - name: Create the service
          ansible.builtin.shell:
            cmd: |
              {{ openstack_cmd }} rating  hashmap service create {{ service_name }}
          ignore_errors: true

        - name: Get the service ID
          ansible.builtin.shell:
            cmd: |
              # export SERVICE_ID=$({{ openstack_cmd }} rating hashmap service list -f value -c Name -c 'Service ID' | grep {{ service_name }} | awk '{ print $2 }')
              {{ openstack_cmd }} rating hashmap service list -f value -c Name -c 'Service ID' | grep {{ service_name }} | awk '{ print $2 }'
          register: service_id
          failed_when: service_id.stdout_lines | length > 1

        - name: Create the field
          ansible.builtin.shell:
            cmd: |
              {{ openstack_cmd }} rating hashmap field create {{ service_id.stdout }} {{ field_name }}
          ignore_errors: true

        - name: Get the field ID
          ansible.builtin.shell:
            cmd: |
              #export FLAVOR_FIELD_ID=$({{ openstack_cmd }} rating hashmap field list {{ service_id.stdout }} -f value -c Name -c 'Field ID' | grep {{ field_name }} | awk '{ print $2}')
              {{ openstack_cmd }} rating hashmap field list {{ service_id.stdout }} -f value -c Name -c 'Field ID' | grep {{ field_name }} | awk '{ print $2}'
          register: flavor_field_id 

        - name: Get the flavor ID
          ansible.builtin.shell:
            cmd: |
              # export FLAVOR_ID=$({{ openstack_cmd }} flavor list -f value -c Name -c ID | grep {{ flavor_name }} | awk '{print $2}')
              {{ openstack_cmd }} flavor list -f value -c Name -c ID | grep {{ flavor_name }} | awk '{print $2}'
          register: flavor_id

        - name: Show the Group and flavor ID
          ansible.builtin.debug:
            var: item
          with_items:
            - group_id
            - flavor_id

        - name: Create the mapping
          ansible.builtin.shell:
            cmd: |
              {{ openstack_cmd }} rating hashmap mapping create 0.01 --field-id {{ flavor_field_id.stdout }}  --value {{ flavor_id.stdout }} -g {{ group_id.stdout }} -t flat

      always:
        - name: Delete the flavor
          ansible.builtin.shell:
            cmd: |
              {{ openstack_cmd }} flavor delete test_flavor
