---
- name: Run pre-test steps
  ansible.builtin.import_playbook: pre-test-steps.yml

- name: Run cloudkitty tests on osp18
  hosts:  "{{ cifmw_target_hook_host | default('localhost')  }}"
  gather_facts: true
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  vars_files:
    - vars/common.yml
    - vars/osp18_env.yml
  tasks:
    - name: Check that the API is available
      ansible.builtin.shell:
        cmd: |
          {{ openstack_cmd }} rating module list
